# Generated by Django 6.0.4 on 2026-04-15 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
