# Generated by Django 4.2.8 on 2026-03-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('MaTK', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenDangNhap', models.CharField(max_length=50, unique=True)),
                ('MatKhau', models.CharField(max_length=20)),
                ('VaiTro', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNV', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('MaTK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKH', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HoTen', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=200)),
                ('MaTK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
            ],
        ),
    ]
