# Generated by Django 6.0.4 on 2026-04-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('MaKM', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenKhuyenMai', models.CharField(max_length=50)),
                ('PhanTramGiam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NgayBatDau', models.DateField()),
                ('NgayKetThuc', models.DateField()),
                ('MoTa', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoiThoaiTuVan',
            fields=[
                ('MaHoiThoai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TrangThai', models.CharField(max_length=50)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuTichDiem',
            fields=[
                ('MaLS', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('DiemThayDoi', models.IntegerField()),
                ('LyDo', models.CharField(max_length=200)),
                ('NgayThucHien', models.DateField()),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='ThongBaoKhuyenMai',
            fields=[
                ('MaTB', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NoiDung', models.CharField(max_length=200)),
                ('NgayGui', models.DateField()),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='TichDiem',
            fields=[
                ('MaTichDiem', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TongDiem', models.IntegerField()),
                ('MaKH', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='TinNhanTuVan',
            fields=[
                ('MaTinNhan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NoiDung', models.CharField(max_length=200)),
                ('ThoiGianGui', models.DateTimeField(auto_now_add=True)),
                ('MaHoiThoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cskh.hoithoaituvan')),
                ('MaNV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nhanvien')),
            ],
        ),
    ]
