# Generated by Django 6.0.3 on 2026-04-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cskh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsutichdiem',
            name='MaNV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.nhanvien'),
        ),
    ]
