# Generated by Django 6.0.3 on 2026-04-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0002_lichsutichdiem_manv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinnhantuvan',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
