# Generated by Django 6.0.3 on 2026-04-29 04:13

import CSKH_04.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cskh', '0003_tinnhantuvan_hinhanh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinnhantuvan',
            name='HinhAnh',
            field=models.ImageField(blank=True, null=True, upload_to=CSKH_04.utils.UnaccentedUploadTo('chat_images/')),
        ),
        migrations.AlterField(
            model_name='tinnhantuvan',
            name='NoiDung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
