# Generated by Django 4.2.8 on 2026-04-03 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cskh', '0001_initial'),
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField(default=0)),
                ('DonGia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ThanhTien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('MaBTSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bienthesanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('MaDonHang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NgayDat', models.DateField()),
                ('NgayGiao', models.DateField(blank=True, null=True)),
                ('TongTien', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TrangThaiDonHang', models.CharField(choices=[('CHO', 'Chờ xử lý'), ('DANG', 'Đang giao'), ('DONE', 'Đã giao')], max_length=50)),
                ('DiaChiGiaoHang', models.CharField(max_length=200)),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
                ('MaKM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cskh.khuyenmai')),
            ],
        ),
        migrations.CreateModel(
            name='DoiTra',
            fields=[
                ('MaDoiTra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('LoaiYeuCau', models.CharField(choices=[('DOI', 'Đổi hàng'), ('TRA', 'Trả hàng - Hoàn tiền')], max_length=50)),
                ('NgayYeuCau', models.DateField()),
                ('LyDo', models.CharField(max_length=200)),
                ('HinhAnh', models.ImageField(upload_to='doitra_images/')),
                ('TrangThai', models.CharField(choices=[('DONE', 'Đã xử lý'), ('PENDING', 'Chờ xử lý'), ('REJECT', 'Từ chối')], max_length=50)),
                ('GhiChuXuLy', models.CharField(max_length=100)),
                ('MaCTDH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.chitietdonhang')),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
                ('MaNV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='MaDonHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.donhang'),
        ),
        migrations.AlterUniqueTogether(
            name='chitietdonhang',
            unique_together={('MaDonHang', 'MaBTSP')},
        ),
    ]
