# Generated by Django 6.0.3 on 2026-04-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietdonhang',
            name='id',
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='MaCTDH',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
