# Generated by Django 4.2.8 on 2026-04-16 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_remove_chitietdonhang_id_chitietdonhang_mactdh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doitra',
            name='GhiChuXuLy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doitra',
            name='MaNV',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.nhanvien'),
        ),
        migrations.AlterField(
            model_name='doitra',
            name='TrangThai',
            field=models.CharField(choices=[('DONE', 'Đã xử lý'), ('PENDING', 'Chờ xử lý'), ('REJECT', 'Từ chối')], default='PENDING', max_length=50),
        ),
    ]
