# Generated by Django 6.0.3 on 2026-04-29 04:13

import CSKH_04.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_doitra_ghichuxuly_alter_doitra_manv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doitra',
            name='HinhAnh',
            field=models.ImageField(upload_to=CSKH_04.utils.UnaccentedUploadTo('doitra_images/')),
        ),
    ]
