# Generated by Django 6.0.4 on 2026-04-15 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=100)),
                ('MoTa', models.CharField(blank=True, max_length=200, null=True)),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('HinhAnh', models.ImageField(upload_to='sanpham/')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDanhGia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoSao', models.IntegerField()),
                ('NoiDung', models.CharField(blank=True, max_length=200, null=True)),
                ('HinhAnh', models.ImageField(blank=True, upload_to='danhgia/')),
                ('NgayDanhGia', models.DateField()),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='BienTheSanPham',
            fields=[
                ('MaBTSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MauSac', models.CharField(max_length=50)),
                ('Size', models.CharField(choices=[('SX', 'SX'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20)),
                ('SoLuongTon', models.IntegerField()),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
            options={
                'db_table': 'products_bienthesanpham',
            },
        ),
    ]
