# Generated by Django 4.2.8 on 2026-03-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('MaSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TenSP', models.CharField(max_length=100)),
                ('MoTa', models.CharField(blank=True, max_length=200, null=True)),
                ('Gia', models.DecimalField(decimal_places=2, max_digits=18)),
                ('HinhAnh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDanhGia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SoSao', models.IntegerField()),
                ('NoiDung', models.CharField(blank=True, max_length=200, null=True)),
                ('HinhAnh', models.CharField(blank=True, max_length=100, null=True)),
                ('NgayDanhGia', models.DateField()),
                ('MaKH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.khachhang')),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietSanPham',
            fields=[
                ('MaCTSP', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MauSac', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=20)),
                ('SoLuongTon', models.IntegerField()),
                ('MaSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
            ],
        ),
    ]
