# Generated by Django 4.2.8 on 2026-04-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bienthesanpham',
            table='products_bienthesanpham',
        ),
    ]
