# Generated by Django 6.0.3 on 2026-04-29 04:13

import CSKH_04.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='HinhAnh',
            field=models.ImageField(blank=True, upload_to=CSKH_04.utils.UnaccentedUploadTo('danhgia/')),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='HinhAnh',
            field=models.ImageField(upload_to=CSKH_04.utils.UnaccentedUploadTo('sanpham/')),
        ),
    ]
